version: '3.8'

services:

  # UI
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - './frontend:/usr/src/app/frontend'
  #     - '/usr/src/app/frontend/node_modules'
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   command: npm run dev
  #   depends_on:
  #     - playroll-backend


  # BACKEND
  playroll-backend:
    build: ./backend
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./backend:/usr/src/app
    # environment:
      # - CELERY_BROKER_URL=redis://shopintel-redis:6379/0
      # - CELERY_RESULT_BACKEND=redis://shopintel-redis:6379/0
    depends_on:
      - playroll-mongodb

      
  # shopintel-worker:
  #   build: ./backend
  #   command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
  #   volumes:
  #     - ./backend:/usr/src/app
  #   environment:
  #     - CELERY_BROKER_URL=redis://shopintel-redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://shopintel-redis:6379/0
  #   depends_on:
  #     - shopintel-backend
  #     - shopintel-redis

  # shopintel-redis:
  #   image: redis:7



  playroll-mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: playroll-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    

volumes:
  mongodb-data:
    driver: local
  static-data:
    driver: local
